### ISSUE TITLE
internationalization to finish

### ISSUE THREAD

**Issue by SebCanet** [BlocklyDuino/BlocklyDuinoReboot#3]
put english sentence in relative variable in block definition, and complete lang.js

enhance other translations

**Comment by philippejadin** [comment]
can you detail where those translations are needed ?

**Comment by SebCanet** [comment]
In each sentence you read at screen, even in blocks.

**Comment by philippejadin** [comment]
it means we need a way to generate all javascript files in BlcoklyDuino, the msae way as in blockly there is build.py

Or maybe we don't care and just includes the files as needed without compressing them. But I'd like to find a way to provide translations inside each block directory instead of elsewhere. Let me think about it :-)

**Comment by philippejadin** [comment]
what is the purpose of en_BD.js ? Can we merge it inside en.js now that we have a separate folder for blockly / blocklyduino messages ?

**Comment by SebCanet** [comment]
The idea was to not merge everything in the same language file, but store BlocklyDuino specific string in a separate folder/file.

**Comment by philippejadin** [comment]
it is already specific to blockly in this directory, no ? we take messages from : 

- /blockly/msg -> original, untouched blockly messages
- /blocklyduino/msg -> our own arduino additions

**Comment by SebCanet** [comment]
Just for modularity I wanted to separate:

- BlocklyDuino\msg\js\en.js for BlocklyDuino only

- BlocklyDuino\msg\js\en_BD for colors, Categories name, blocks text

As we can add js file, it may be difficult to find out a string in a file with  23867546 lines :-D

**Comment by philippejadin** [comment]
Ok then I propose : 

- colors and similar stuff in constants.js (since it doesn't depend on language), blockly does it that way : https://github.com/google/blockly/blob/master/msg/json/constants.json
- categories in main en.js
- block specific translation inside blocks. I will make a proposal. Additional categories could be defined inside blocks as well (for block that requires special categories)

**Comment by philippejadin** [comment]
Do you understand how this whole translation system works in blockly? It's so complicated just for what it need to do... For example this strange syntax : "%{BKY}", how is it parsed?
I already asked in their google group btw

**Comment by SebCanet** [comment]
I think it's a Scratch3 effect, they seem to use more and more JSON format, relative information, etc.
In doc: https://developers.google.com/blockly/guides/create-custom-blocks/block-colour

**Comment by SebCanet** [comment]
finished
